site_name: AYYAPPASWAMY EETHAKOTA

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - privacy

 
nav:
  - Home:
      - Professional Summary: Home/Professional-Summary.md
      - Technical Skills: Home/technical-skills.md
      - Roles & Responsibilities: Home/roles-responsibilities.md
      - Professional Experience: Home/professional-experience.md
      - Projects: Home/projects.md
      - Education: Home/education.md
      - Contact: Home/contact.md

  - Documents:
      - GitHub Pages CI/CD: Documents/GitHub_Pages_MkDocs.md
      - Linux Commands: Documents/Linux_commands.md
      - LVM: Documents/Logical Volume Manager (LVM).md
      - Python: Documents/Python.md
      - Anaconda: Documents/Anaconda.md
      - OpenMPI: Documents/OpenMpi.md
      - METIS: Documents/Metis.md
      - Proxy: Documents/Proxy.md
      - Local Repo: Documents/Local_repo.md
      - Hyperthreading: Documents/hyperthreading.md
      - Slurm Basics: Documents/Slurm.md
      - SU2 : Documents/SU2_Installation.md
      
      - Scripts:
          - Run Script: Documents/Scripts/run.sh.md

  - Troubleshooting:
      - Overview: Troubleshooting/index.md
      - Hardware Troubleshooting : Troubleshooting/Hardware Troubleshooting.md
      - Power Drain : Troubleshooting/Power Drain.md
      - Power Supply Unit (PSU) : Troubleshooting/Power Supply Unit.md
      - Memory issue : Troubleshooting/Memory issue.md
      - Processor : Troubleshooting/Processor-replaceing.md


