site_name: AYYAPPASWAMY EETHAKOTA

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune

# Remove the generator notice
extra:
  generator: false

# Optionally, hide the entire footer
hide:
  - footer


palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - privacy

 
nav:
  - Home: index.md

  - Profile:
      - Professional Summary: Home/Professional-Summary.md
      - Technical Skills: Home/technical-skills.md
      - Professional Experience: Home/professional-experience.md
      - Roles & Responsibilities: Home/roles-responsibilities.md
      - Applications & Libraries: Home/Applications&Libraries.md
      - Projects: Home/projects.md
      
      
      

  - Documents:
      - Important Note : Documents/index.md
      - Anaconda: Documents/Anaconda.md
      - GitHub Pages CI/CD: Documents/GitHub_Pages_MkDocs.md
      - Hyperthreading: Documents/hyperthreading.md
      - Linux Commands: Documents/Linux_commands.md
      - LVM: Documents/Logical Volume Manager (LVM).md
      - Local Repo: Documents/Local_repo.md
      - METIS: Documents/Metis.md
      - What is module file : Documents/Module-File.md
      - NFS : Documents/NFS.md
      - OpenMPI: Documents/OpenMpi.md
      - PIP: Documents/PIP.md
      - Python-3.14.3: Documents/Python-Offline.md
      - Proxy: Documents/Proxy.md            
      - Slurm Basics: Documents/Slurm.md
      - SU2 : Documents/SU2_Installation.md
      
      
      
      - Lustre File System:
          - Lustre: Documents/Lustre.md
          - Installation: Documents/lustre-installtion.md

      
      - Scripts:
          - Run Script: Documents/Scripts/run.sh.md

  - Troubleshooting:
      - Overview: Troubleshooting/index.md
      - Hardware Troubleshooting : Troubleshooting/Hardware Troubleshooting.md
      - Power Drain : Troubleshooting/Power Drain.md
      - Power Supply Unit (PSU) : Troubleshooting/Power Supply Unit.md
      - Memory issue : Troubleshooting/Memory issue.md
      - Processor : Troubleshooting/Processor-replaceing.md

      
  - Contact: Home/contact.md
